# Generated by Django 4.2 on 2025-01-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
