# Generated by Django 4.2 on 2025-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
